#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser

        self.login_and_go("/sapientcot")

        b.wait_visible("[data-testid=sapientcot-app]")
        b.wait_visible("[data-testid=sapientcot-service-card]")
        b.wait_visible("[data-testid=sapientcot-tls-card]")
        b.wait_visible("[data-testid=sapientcot-config-card]")

        b.set_layout("medium")
        b.click("#sapientcot-debug-expand")
        b.wait_js_cond("document.querySelector('#app').scrollHeight > document.querySelector('#app').clientHeight")
        b.eval_js("document.querySelector('#app').scrollTop = document.querySelector('#app').scrollHeight")
        b.wait_js_cond("document.querySelector('#app').scrollTop > 0")


if __name__ == '__main__':
    testlib.test_main()
